Update Detector Parameter Descriptions
AprilRobotics/apriltag pull request #223
Opened 2022-03-21 14:25 UTC by QuentinTorg

This PR updates the comments about parameters in the apriltag detector to give the user a better understanding of valid ranges and default values

2022-03-21 14:27 UTC, QuentinTorg commented on apriltag.h
> -    // quad_decimate = 1.
Option is no longer ignored if quad decimate is 1: https://github.com/AprilRobotics/apriltag/blob/master/apriltag.c#L895

2022-03-21 17:27 UTC, christian-rauch requested changes
Please merge your fixup commits. I.e. you have two commits that change the same part twice. Merge them to make the history more readable.

2022-03-21 17:27 UTC, christian-rauch commented on apriltag.h
> +    // 1.5 -> 1.999       7
This table is a bit confusing. You are referring to the look-up table for equation "kernel_size = 4 * abs(quad_sigma)":
https://github.com/AprilRobotics/apriltag/blob/bee5efb1cc263ec1459bca46193e3428220d52ba/apriltag.c#L1020-L1027

But why this mapping from 0 to 0.499, 0.5 to 0.999, etc.? That looks like 0.0 gives you 0.499 and 0.5 gives you 0.999. Do you mean that all values in this range map to the same kernel size?

The notation is a bit confusing and I would personally prefer if this is just properly formalised. With an ASCII or LaTeX function.

2022-05-19 10:32 UTC, christian-rauch commented
@QuentinTorg Are you interested in continuing with this?

2022-12-04 22:04 UTC, closed without merging