Add back Ubuntu 16.04 support - resolves #244
AprilRobotics/apriltag pull request #245
Opened 2022-07-20 10:44 UTC by wxmerkt

We need to define `_GNU_SOURCE` for the initially reported error to go away. 

Since Ubuntu 16.04 ships by default with OpenCV 2.4, we need further changes for renamed variables and moved modules (`TickMeter` was in `contrib` back in 2.4).

Resolves #244

2022-07-20 20:17 UTC, wxmerkt reviewed
Deactivate submodule checkout

2022-07-20 21:45 UTC, wxmerkt commented
I've removed the Kinetic config from the ROS-tooling CI again - it wasn't building. I believe this PR is ready for merging

2022-07-21 05:50 UTC, christian-rauch requested changes
If the CI fails for Ubuntu 16.04 then maybe just squash the commits again so that it appears as if we never added it.

2022-07-21 17:53 UTC, christian-rauch approved these changes

2022-07-21 19:19 UTC, merged