Fix spurious wake-ups and worker threads initialization in workerpool
AprilRobotics/apriltag pull request #339
Opened 2024-06-24 14:01 UTC by berteauxjb

I encountered random segfaults while using this library and tried to figure out what was happening. I isolated the segfault to the function `worker_thread()` of `workerpool.c`. Long story short, there is no predicate that prevents `worker_thread()` from running if it is woken up spuriously and a task has already been added. Since there is no mutex used in `workerpool_add_task()`, it is possible for the zarray `wp->tasks` to be reallocated, rendering the volatile pointer `task` in `worker_thread()` invalid and causing a segfault.

This PR addresses this issue by adding a predicate and shielding calls that access `wp` behind a mutex. I also saw issue #70 and agree that the initialization of the worker threads might lead to race conditions, so I addressed that too.

2024-06-24 18:20 UTC, christian-rauch commented
Thanks for the PR. I approved the CI for this PR. The tests crash on Windows (`Exception: SegFault`). Any idea what is going on there?

2024-06-25 21:21 UTC, berteauxjb commented
> Thanks for the PR. I approved the CI for this PR. The tests crash on Windows (`Exception: SegFault`). Any idea what is going on there?

I was able to reproduce on a Windows machine :smile: It turns out that the `wp->mutex` is only initialized if `wp->nthreads > 1`. In the test there is only 1 thread, and `workerpool_add_task` was accessing a non-initialized mutex. I shielded the usage of the mutex with `if (wp->nthreads > 1)` like it's done in other places in the file.

2024-06-26 07:11 UTC, christian-rauch requested changes
Final request: Can you now squash your fixup commit https://github.com/AprilRobotics/apriltag/pull/339/commits/737ff6b80c32dadb8a470cf38e113f9dffab204b into the original commit https://github.com/AprilRobotics/apriltag/pull/339/commits/be17a2d667f668b05944cfa0e8577e3f262babdc and force-push again with the clean git history?

2024-06-26 08:17 UTC, berteauxjb commented
> Final request: Can you now squash your fixup commit [737ff6b](https://github.com/AprilRobotics/apriltag/commit/737ff6b80c32dadb8a470cf38e113f9dffab204b) into the original commit [be17a2d](https://github.com/AprilRobotics/apriltag/commit/be17a2d667f668b05944cfa0e8577e3f262babdc) and force-push again with the clean git history?

Done!

2024-06-26 08:20 UTC, christian-rauch approved these changes

2024-06-26 08:26 UTC, christian-rauch commented
Thanks a lot!

2024-06-26 08:27 UTC, merged